/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vlPuGdAmPvu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardHeader, CardContent, Card } from "@/components/vercel/ui/card"
import { JSX, SVGProps } from "react"

export default function landingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <CarIcon className="h-6 w-6" />
          <span className="sr-only">Cargram</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Explore
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Groups
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Upload
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Profile
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full h-[70vh] bg-[url(/hero-image.jpg)] bg-cover bg-center flex items-center justify-center">
          <div className="px-4 md:px-6 text-center space-y-4 bg-black/50 p-8 rounded-lg">
            <h1 className="text-3xl sm:text-5xl font-bold text-white">Welcome to CarSnap</h1>
            <p className="text-lg text-gray-200">
              Share your passion for cars and connect with like-minded enthusiasts.
            </p>
            <div className="flex justify-center gap-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#f39c12] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                href="#"
              >
                Sign Up
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-[#f39c12] bg-transparent px-8 text-sm font-medium text-[#f39c12] shadow-sm transition-colors hover:bg-[#f39c12] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                href="#"
              >
                Log In
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Latest Car Photos</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore the latest car photos shared by our community.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <img
                  alt="Car Photo"
                  className="w-full h-auto rounded-lg object-cover"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Popular Car Groups</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Join the conversation and connect with other car enthusiasts.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Supercars</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss the latest supercars and exotic vehicles.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Classic Cars</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss and share your passion for classic cars.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Electric Vehicles</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss the latest developments in electric vehicles.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Tuning and Modifications</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss and share your car modification projects.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Racing and Motorsports</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss the latest news and events in the world of racing.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Vintage and Collector Cars</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss and share your passion for vintage and collector cars.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Join Group
                      </Link>
                    </div>
                  </CardContent>
                </Card>
                <Card className="bg-white dark:bg-gray-950 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <img
                      alt="Car Group"
                      className="w-full h-auto rounded-t-lg object-cover"
                      height="200"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "300/200",
                        objectFit: "cover",
                      }}
                      width="300"
                    />
                  </CardHeader>
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold">Off-Road and Overlanding</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-2">
                      Discuss and share your adventures in off-road and overlanding.
                    </p>
                    <div className="mt-4">
                      <Link
                        className="inline-flex h-9 items-center justify-center rounded-md bg-[#f39c12] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#e67e22] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#f39c12] disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      />
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>
  )
}
